# Generated by Django 5.2.4 on 2025-08-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('employer', 'Employer')], max_length=10),
        ),
    ]
