# Generated by Django 5.2.4 on 2025-08-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
