# Generated by Django 5.2.4 on 2025-08-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_employerprofile_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="external_links",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
