# Generated by Django 5.2.4 on 2025-08-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_studentprofile_external_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="documents",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="profile_links",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
